shell/update_vsan_observer_offline_files.sh

Fixed an issues where font-awesome.css was located into the js directory.

Changed targetlocation of font-awesome.css

---

shell/update_vsan_observer_offline_files.sh

Removed Line 42: cp ${VSAN_OBSERVER_STAT_FILE}.bak ${VSAN_OBSERVER_STAT_FILE}

Fixed stats.erb.html not being updated

---

powershell/xMove-VM.ps1

Enables compute-only xVC vMotion for VMs with disks on different datastores.

Compute-only xVC vMotion

---

powershell/GenerateVMConsoleURL.ps1

(Newline added to last line by GitHub in-browser editor.)

Fix typo in comment

---

perl/AppUtil/HostUtil.pm
perl/AppUtil/VMUtil.pm
perl/AppUtil/XMLInputUtil.pm
perl/schema/vGhettoClone_extended.xsd
perl/vGhettoClone_extended.pl
perl/vGhettoLinkedClone.pl
perl/vGhettoLinkedClone_linux.pl

Glad to see you added your scripts to Github.   
Here's a modification that I've been using for quite some time, that I just merged into your current version.   It will move the newly created clone to a vSphere folder by specifying the folder on the command line with the option '--folder'.
Maybe others will find this modification useful too.

Add a function to move the clone into a specified folder in the vCenter

---

perl/vmwarevSphereSecurityHardeningReportCheck.pl

Updated for compatibility with vSphere 5.5/6.0

Updated compatibility for vSphere 5.5/6.0

---

.gitignore
perl/vmwarevSphereHealthCheck.pl

vmwarevSphereHealthCheck.pl: Fix/simplify prettyPrintData. Allow SDRS pod to have 0 datastores.
Fix minor issue introduced for 6.0.0 hosts in 7e3c7b9bffa4eb2174203f01e1402c8176cf77cf.
Make indentation consistent,

vmwarevSphereHealthCheck.pl: Fix/simplify prettyPrintData. Allow SDRS pod to have 0 datastores.

---

powershell/VerifyESXiMicrocodePatch.ps1

STIBPass used instead of STIBPPass

Variable typo in Verify-ESXiMicrocodePatch

---

powershell/VerifyESXiMicrocodePatch.ps1

This adds a column named IntelSightings to the output of Verify-ESXiMicrocodePatch based on the information in https://kb.vmware.com/s/article/52345
@lamw Let me know if you figure out a good way to check out the currently loaded microcode version.

Add Intel Sighting checks to Verify-ESXiMicrocodePatch

---

powershell/VerifyESXiMicrocodePatch.ps1

Family always worked anyway since Extended Family isn't really used. Model and Stepping were wrong though. Defaulted FMS to decimal for future changes, procSig is usually only ever displayed as hex so left it as is (and merged to one line).

fixed Intel FMS calculation

---

powershell/VerifyESXiMicrocodePatch.ps1

fixed what I broke (cpuModel) and removed superfluous white-spaces 
nibble ...
added FMS to final table, forgot that earlier

 fixed CPU Model Name and added FMS to output

---

powershell/VerifyESXiMicrocodePatch.ps1

This update changes how script identifies vmx version and if Hypervisor Assisted Guest Mitigation is applicable or not.
Resolves an issue where vSphere 6.7 VMs with vmx-14 were not properly identified.

Update VerifyESXiMicrocodePatch.ps1 to support vmx-14 and later versions

---

powershell/xNew-VM.ps1

Couple of changes were needed. 
1. Passing snapshot name to the function (line #204)
2. Adding mandatory parameter to Get-snapshot i.e. -VM (line #89)

Cloning from snapshot change

---

powershell/ESXiDisableProtocolConfiguration.ps1

Greetings William!
I've been a big fan of yours for several years, you have saved me many hours with PowerCLI scripts. I came across your script for changing TLS versions, noticed I was having problems, and determined it was from being connected to multiple vCenters. Hope you don't mind a pull request with my hack to your code?
Thanks again for all you do!

Adding warning/return when connected to multiple vCenters

---

powershell/xNew-VM.ps1

Removed superfluous '$' in xNew-VM call.
This is my first ever pull request; please be gentle.  :-)

Fixed typo in xNew-VM call.

---

powershell/VMKeystrokes.ps1

Hi,
Following conversation on twitter, a series of patches for enhance VMKeyStrokes !

Enhance VMKeyStrokes

---

powershell/GenerateVMConsoleURL.ps1

Simple replace for the correct `"` to be used.  Ran into problems depending on the PS version used

invalid character used for quote

---

python/make_vcsp_2022.py

AZ Blob Support

---

powershell/GlobalPermissions.ps1

Updated reference URL

---

python/vsan-enable-perf-service.py

- More comments
- Removed `profile` spec as not needed as per [docs](https://vdc-download.vmware.com/vmwb-repository/dcr-public/3325c370-b58c-4799-99ff-58ae3baac1bd/45789cc5-aba1-48bc-a320-5e35142b50af/doc/vim.cluster.VsanPerfsvcConfig.html), default vSAN policy used if not specified
- Includes waiting for task completion of cluster reconfiguration
- Outputs state of the task once completed
- Exists with 0 on success, 1 otherwise

Some minor changes to vsan-enable-perf-service.py
